"""Generate the device's mascot bitmaps from assets/mascot/nous-girl-white-1024.png.

Output: firmware/core/src/mascot_data.cpp. It holds 1-bit, row-major,
MSB-first bitmaps ("ink" = the white artwork) for every size in SIZES and
every frame in FRAMES, plus anchor points the UI uses for its effects.

    python tools/gen_mascot.py            # regenerate the C++ source
    python tools/gen_mascot.py --preview  # also write build/mascot-preview.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw

REPO = Path(__file__).resolve().parents[1]
MASTER = REPO / "assets" / "mascot" / "nous-girl-white-1024.png"
OUT = REPO / "firmware" / "core" / "src" / "mascot_data.cpp"

SIZES = (64, 96, 144, 192)
FRAMES = ("idle", "blink", "talk")
THRESHOLD = 110  # alpha above this is ink after downsampling

# Feature geometry in 1024-px master coordinates.
RIGHT_EYE = [(318, 418), (452, 410), (462, 470), (444, 498), (326, 496), (314, 458)]
RIGHT_LID = [(326, 452), (350, 466), (388, 474), (424, 468), (452, 452)]
LEFT_EYE = [(213, 446), (254, 444), (257, 516), (215, 518)]
LEFT_LID = [(215, 484), (233, 490), (254, 484)]
MOUTH_OPEN = (246, 622, 292, 648)  # ellipse box between the lips
# Effect anchors (fractions of the bitmap size, x1000).
EAR_CUP = (622, 300)    # the headphone cup: "listening" waves radiate from here
MOUTH = (268, 635)      # "speaking" waves
HEAD_TOP_RIGHT = (820, 110)  # "thinking" dots
EYES_ROWS = (405, 520)  # rows touched by blinking
MOUTH_ROWS = (600, 665)  # rows touched by talking


def make_frames(master: Image.Image) -> dict[str, Image.Image]:
    alpha = master.getchannel("A")
    frames = {"idle": alpha}

    blink = alpha.copy()
    d = ImageDraw.Draw(blink)
    d.polygon(RIGHT_EYE, fill=255)  # skin over the open eye
    d.polygon(LEFT_EYE, fill=255)
    d.line(RIGHT_LID, fill=0, width=14, joint="curve")  # closed lids
    d.line(LEFT_LID, fill=0, width=12, joint="curve")
    frames["blink"] = blink

    talk = alpha.copy()
    ImageDraw.Draw(talk).ellipse(MOUTH_OPEN, fill=0)
    frames["talk"] = talk
    return frames


def to_bits(alpha: Image.Image, size: int) -> bytes:
    small = alpha.resize((size, size), Image.LANCZOS)
    px = small.load()
    out = bytearray()
    for y in range(size):
        byte, nbits = 0, 0
        for x in range(size):
            byte = (byte << 1) | (1 if px[x, y] > THRESHOLD else 0)
            nbits += 1
            if nbits == 8:
                out.append(byte)
                byte, nbits = 0, 0
        if nbits:
            out.append(byte << (8 - nbits))
    return bytes(out)


def emit(frames: dict[str, Image.Image]) -> str:
    lines = [
        "// Generated by tools/gen_mascot.py from assets/mascot/nous-girl-white-1024.png. Do not edit.",
        "// Artwork: Hermes Agent mascot (MIT License, Copyright (c) 2025 Nous Research).",
        '#include "hg/mascot.hpp"',
        "",
        "namespace hg::mascot {",
        "namespace {",
        "",
    ]
    table = []
    for size in SIZES:
        for frame in FRAMES:
            name = f"k{frame.capitalize()}{size}"
            data = to_bits(frames[frame], size)
            lines.append(f"const uint8_t {name}[{len(data)}] = {{")
            for i in range(0, len(data), 24):
                lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
            lines.append("};")
            table.append((size, frame, name))
    lines.append("")
    lines.append("const Bitmap kBitmaps[] = {")
    for size, frame, name in table:
        lines.append(f"    {{{size}, Frame::{frame.capitalize()}, {name}}},")
    lines += [
        "};",
        "",
        f"const Anchors kAnchors = {{{{{EAR_CUP[0]}, {EAR_CUP[1]}}}, {{{MOUTH[0]}, {MOUTH[1]}}}, "
        f"{{{HEAD_TOP_RIGHT[0]}, {HEAD_TOP_RIGHT[1]}}}, {EYES_ROWS[0]}, {EYES_ROWS[1]}, "
        f"{MOUTH_ROWS[0]}, {MOUTH_ROWS[1]}}};",
        "",
        "}  // namespace",
        "",
        "const Anchors& anchors() { return kAnchors; }",
        "",
        "const Bitmap* pick(int max_size, Frame frame) {",
        "  const Bitmap* best = nullptr;",
        "  for (const auto& b : kBitmaps) {",
        "    if (b.frame != frame) continue;",
        "    if (b.size <= max_size && (!best || b.size > best->size)) best = &b;",
        "  }",
        "  if (best) return best;",
        "  for (const auto& b : kBitmaps) {",
        "    if (b.frame == frame && (!best || b.size < best->size)) best = &b;",
        "  }",
        "  return best;",
        "}",
        "",
        "}  // namespace hg::mascot",
        "",
    ]
    return "\n".join(lines)


def preview(frames: dict[str, Image.Image], path: Path) -> None:
    pad, scale = 8, 3
    width = sum(s * scale + pad for s in SIZES) + pad
    height = len(FRAMES) * (max(SIZES) * scale + pad) + pad
    sheet = Image.new("RGB", (width, height), (10, 14, 20))
    y = pad
    for frame in FRAMES:
        x = pad
        for size in SIZES:
            small = frames[frame].resize((size, size), Image.LANCZOS).point(lambda v: 255 if v > THRESHOLD else 0)
            tile = Image.new("RGB", (size, size), (10, 14, 20))
            tile.paste(Image.new("RGB", (size, size), (232, 238, 242)), (0, 0), small.convert("L"))
            sheet.paste(tile.resize((size * scale, size * scale), Image.NEAREST), (x, y))
            x += size * scale + pad
        y += max(SIZES) * scale + pad
    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--preview", action="store_true")
    args = ap.parse_args()
    master = Image.open(MASTER).convert("RGBA")
    if master.size != (1024, 1024):
        raise SystemExit(f"{MASTER} must be 1024x1024, got {master.size}")
    frames = make_frames(master)
    OUT.write_text(emit(frames), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    if args.preview:
        path = REPO / "build" / "mascot-preview.png"
        preview(frames, path)
        print(f"wrote {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
